// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: copyfrom_sqlc.go

package models

import (
	"context"
)

// iteratorForCreateEvents implements pgx.CopyFromSource.
type iteratorForCreateEvents struct {
	rows                 []CreateEventsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateEvents) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateEvents) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].OccurAt,
		r.rows[0].ExternalID,
		r.rows[0].Neighborhood,
		r.rows[0].LocationType,
		r.rows[0].CrimeType,
		r.rows[0].Region,
		r.rows[0].Lat,
		r.rows[0].Long,
	}, nil
}

func (r iteratorForCreateEvents) Err() error {
	return nil
}

func (q *Queries) CreateEvents(ctx context.Context, arg []CreateEventsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"events"}, []string{"occur_at", "external_id", "neighborhood", "location_type", "crime_type", "region", "lat", "long"}, &iteratorForCreateEvents{rows: arg})
}
