// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package models

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CrimeType string

const (
	CrimeTypeAssault               CrimeType = "Assault"
	CrimeTypeAutoTheft             CrimeType = "Auto Theft"
	CrimeTypeTheftfromMotorVehicle CrimeType = "Theft from Motor Vehicle"
	CrimeTypeBreakandEnter         CrimeType = "Break and Enter"
	CrimeTypeSexualViolation       CrimeType = "Sexual Violation"
	CrimeTypeRobbery               CrimeType = "Robbery"
	CrimeTypeTheftOver             CrimeType = "Theft Over"
	CrimeTypeBikeTheft             CrimeType = "Bike Theft"
	CrimeTypeShooting              CrimeType = "Shooting"
	CrimeTypeHomicide              CrimeType = "Homicide"
)

func (e *CrimeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CrimeType(s)
	case string:
		*e = CrimeType(s)
	default:
		return fmt.Errorf("unsupported scan type for CrimeType: %T", src)
	}
	return nil
}

type NullCrimeType struct {
	CrimeType CrimeType
	Valid     bool // Valid is true if CrimeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCrimeType) Scan(value interface{}) error {
	if value == nil {
		ns.CrimeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CrimeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCrimeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CrimeType), nil
}

type Area struct {
	ID        int32
	CreatedAt pgtype.Timestamptz
	UserID    string
	IsActive  bool
	Address   string
	Region    interface{}
	Radius    float64
	Point     interface{}
	Lat       float64
	Long      float64
}

type Event struct {
	ID           int32
	CreatedAt    pgtype.Timestamptz
	OccurAt      pgtype.Timestamptz
	ExternalID   string
	Neighborhood pgtype.Text
	LocationType pgtype.Text
	CrimeType    CrimeType
	Region       string
	Point        interface{}
	Lat          float64
	Long         float64
}

type Report struct {
	ID         pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	IsReported bool
	AreaID     int32
}

type Scan struct {
	CreatedAt pgtype.Timestamptz
	ReportID  pgtype.UUID
	EventID   int32
}
